development:
  adapter: postgresql
  database: activitiesapi_dev
  host: localhost
  port: 5432  

test:
  adapter: postgresql
  database: activitiesapi_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  port: 5432  
